/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.Auth;

import com.mycompany.quanlydiemtruongthpt.Controller.*;
import com.mycompany.quanlydiemtruongthpt.Model.DanToc;
import com.mycompany.quanlydiemtruongthpt.Model.GiaoVien;
import com.mycompany.quanlydiemtruongthpt.Model.MonHoc;
import com.mycompany.quanlydiemtruongthpt.Model.TonGiao;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class RegisterFirst extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFirst
     */
    public RegisterFirst() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        loadCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        giaoVienCtrl = new GiaoVienCtrl();
        danTocCtrl = new DanTocCtrl();
        tonGiaoCtrl = new TonGiaoCtrl();
        monHocCtrl = new MonHocCtrl();


        jLabelRegister = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelHoTen = new javax.swing.JLabel();
        jTextFieldHoTen = new javax.swing.JTextField();
        jLabelGioiTinh = new javax.swing.JLabel();
        jComboBoxGioiTinh = new javax.swing.JComboBox<>();
        jLabelNgaySinh = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabelDiaChi = new javax.swing.JLabel();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jLabelSdt = new javax.swing.JLabel();
        jTextFieldSdt = new javax.swing.JTextField();
        jLabelDanToc = new javax.swing.JLabel();
        jComboBoxDanToc = new javax.swing.JComboBox<>();
        jLabelTonGiao = new javax.swing.JLabel();
        jComboBoxTonGiao = new javax.swing.JComboBox<>();
        jButtonRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMonHoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRegister.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabelRegister.setText("ĐĂNG KÝ LẦN ĐẦU CHO ADMIN");

        jLabelHoTen.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabelHoTen.setText("Họ và tên:");

        jLabelGioiTinh.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabelGioiTinh.setText("Giới tính:");

        jComboBoxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelNgaySinh.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabelNgaySinh.setText("Ngày sinh:");

        jLabelDiaChi.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabelDiaChi.setText("Địa chỉ:");

        jLabelSdt.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabelSdt.setText("Sđt:");

        jLabelDanToc.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabelDanToc.setText("Dân tộc:");

        jComboBoxDanToc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelTonGiao.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabelTonGiao.setText("Tôn giáo:");

        jComboBoxTonGiao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonRegister.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonRegister.setText("Đăng Ký");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonRegisterActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel1.setText("Môn học:");

        jComboBoxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Mật khẩu:");

        jLabel3.setText("Username:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(jLabelRegister)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHoTen)
                            .addComponent(jLabelGioiTinh)
                            .addComponent(jLabelDiaChi)
                            .addComponent(jLabelSdt)
                            .addComponent(jLabelDanToc)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabelTonGiao)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxTonGiao, 0, 180, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabelNgaySinh))
                            .addComponent(jComboBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jTextFieldSdt)
                            .addComponent(jTextFieldDiaChi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNgaySinh)
                        .addComponent(jLabelGioiTinh))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDiaChi)
                    .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSdt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDanToc)
                    .addComponent(jComboBoxDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTonGiao)
                    .addComponent(jComboBoxTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButtonRegister)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonRegisterActionPerformed
        GiaoVien giaoVien = new GiaoVien();
        String hoTen = jTextFieldHoTen.getText();       giaoVien.setHoTen(hoTen);
        String gioiTinh = (String) jComboBoxGioiTinh.getSelectedItem(); giaoVien.setGioiTinh(gioiTinh);
        String diaChi = jTextFieldDiaChi.getText(); giaoVien.setDiaChi(diaChi);
        String sdt = jTextFieldSdt.getText(); giaoVien.setSoDienThoai(sdt);

        Date date = jDateChooser1.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngaySinh = dateFormat.format(date); giaoVien.setNgaySinh(ngaySinh);

        String str = (String) jComboBoxDanToc.getSelectedItem();
        String[] parts = str.split("-");
        int idDanToc = Integer.parseInt(parts[0].trim());giaoVien.setDanToc_Id(idDanToc);

        String str2 = (String) jComboBoxTonGiao.getSelectedItem();
        String[] parts2 = str.split("-");
        int idTonGiao = Integer.parseInt(parts2[0].trim()); giaoVien.setTonGiao_Id(idTonGiao);

        String str3 = (String) jComboBoxMonHoc.getSelectedItem();
        String[] parts3 = str.split("-");
        int idMonHoc = Integer.parseInt(parts3[0].trim()); giaoVien.setMonHoc_Id(idMonHoc);

        String userName = jTextFieldUsername.getText();
        String password = Arrays.toString(jPasswordField.getPassword());

        new UserCtrl().createAccount(userName, password,giaoVien, true);

        dispose();
        Login login = new Login();
        login.setVisible(true);


    }//GEN-LAST:event_jButtonRegisterActionPerformed


    private void loadCombobox() throws SQLException {
        jComboBoxGioiTinh.removeAllItems();
        jComboBoxMonHoc.removeAllItems();
        jComboBoxDanToc.removeAllItems();
        jComboBoxTonGiao.removeAllItems();

        jComboBoxGioiTinh.addItem("Nam");
        jComboBoxGioiTinh.addItem("Nữ");

        List<DanToc> danTocs = danTocCtrl.getAllDanToc();
        for (int i = 0; i<danTocs.size(); i++) {
            jComboBoxDanToc.addItem(danTocs.get(i).getId()+"-"+danTocs.get(i).getTenDanToc());
        }

        List<TonGiao> tonGiaos = tonGiaoCtrl.getAllTonGiao();
        for (int i = 0; i<tonGiaos.size(); i++) {
            jComboBoxTonGiao.addItem(tonGiaos.get(i).getId()+"-"+tonGiaos.get(i).getTenTonGiao());
        }

        List<MonHoc> monHocs = monHocCtrl.getAllMonHoc();
        for (int i = 0 ; i<monHocs.size();i++) {
            jComboBoxMonHoc.addItem(monHocs.get(i).getId()+"-"+monHocs.get(i).getTenMonHoc());
        }


    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisterFirst().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JComboBox<String> jComboBoxDanToc;
    private javax.swing.JComboBox<String> jComboBoxGioiTinh;
    private javax.swing.JComboBox<String> jComboBoxMonHoc;
    private javax.swing.JComboBox<String> jComboBoxTonGiao;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDanToc;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JLabel jLabelGioiTinh;
    private javax.swing.JLabel jLabelHoTen;
    private javax.swing.JLabel jLabelNgaySinh;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelSdt;
    private javax.swing.JLabel jLabelTonGiao;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldHoTen;
    private javax.swing.JTextField jTextFieldSdt;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private GiaoVienCtrl giaoVienCtrl;
    private DanTocCtrl danTocCtrl;
    private TonGiaoCtrl tonGiaoCtrl;
    private MonHocCtrl monHocCtrl;
}
