/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.QuanLy;

import com.mycompany.quanlydiemtruongthpt.Controller.DanTocCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.HoSoHocSinhCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.LopCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.TonGiaoCtrl;
import com.mycompany.quanlydiemtruongthpt.DAO.DanTocDAO;
import com.mycompany.quanlydiemtruongthpt.DAO.HoSoHocSinhDAO;
import com.mycompany.quanlydiemtruongthpt.DAO.LopDAO;
import com.mycompany.quanlydiemtruongthpt.DAO.TonGiaoDAO;
import com.mycompany.quanlydiemtruongthpt.Model.DanToc;
import com.mycompany.quanlydiemtruongthpt.Model.HoSoHocSinh;
import com.mycompany.quanlydiemtruongthpt.Model.Lop;
import com.mycompany.quanlydiemtruongthpt.Model.TonGiao;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class HocSinhQL extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_1
     */
    public HocSinhQL() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        loadDanhSachHoSoHocSinh();
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        hoSoHocSinhCtrl = new HoSoHocSinhCtrl();
        newhoSoHocSinh = new HoSoHocSinh();
        lopCtrl = new LopCtrl();
        lopDAO = new LopDAO();
        tonGiaoDAO = new TonGiaoDAO();
        tonGiaoCtrl = new TonGiaoCtrl();
        danTocCtrl = new DanTocCtrl();
        danTocDAO = new DanTocDAO();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelHoVaTenHS = new javax.swing.JLabel();
        jTextFieldHoVaTenHS = new javax.swing.JTextField();
        jLabelGioiTinh = new javax.swing.JLabel();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jLabelNgaySinh = new javax.swing.JLabel();
        jDateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabelNoiSinh = new javax.swing.JLabel();
        jTextFieldNoiSinh = new javax.swing.JTextField();
        jLabelDanToc = new javax.swing.JLabel();
        jComboBoxDanToc = new javax.swing.JComboBox<>();
        jLabelTonGiao = new javax.swing.JLabel();
        jComboBoxTonGiao = new javax.swing.JComboBox<>();
        jLabelHoTenCha = new javax.swing.JLabel();
        jTextFieldHoTenCha = new javax.swing.JTextField();
        jLabelNamSinhCha = new javax.swing.JLabel();
        jTextFieldNamSinhCha = new javax.swing.JTextField();
        jLabelNgheNghiep = new javax.swing.JLabel();
        jTextFieldNgheNghiep = new javax.swing.JTextField();
        jLabelNamSinhMe = new javax.swing.JLabel();
        jLabelHoTenMe = new javax.swing.JLabel();
        jLabelSdtCha = new javax.swing.JLabel();
        jTextFieldSdtCha = new javax.swing.JTextField();
        jTextFieldHoTenMe = new javax.swing.JTextField();
        jTextFieldNamSinhMe = new javax.swing.JTextField();
        jButtonThemHocSinh = new javax.swing.JButton();
        jLabelNgheNghiepMe = new javax.swing.JLabel();
        jLabelSdtMe = new javax.swing.JLabel();
        jTextFieldNgheNghiepMe = new javax.swing.JTextField();
        jTextFieldSdtMe = new javax.swing.JTextField();
        jLabelLop = new javax.swing.JLabel();
        jComboBoxLop = new javax.swing.JComboBox<>();
        jButtonThoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachHocSinh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonXemChiTiet = new javax.swing.JButton();
        jButtonChinhSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ HỌC SINH");
        setAutoRequestFocus(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin học sinh");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelHoVaTenHS.setText("Họ và tên:");

        jLabelGioiTinh.setText("Giới tính:");

        buttonGroup1.add(jRadioButtonNam);
        jRadioButtonNam.setSelected(true);
        jRadioButtonNam.setText("Nam");

        buttonGroup1.add(jRadioButtonNu);
        jRadioButtonNu.setText("Nữ");

        jLabelNgaySinh.setText("Ngày sinh:");

        jLabelNoiSinh.setText("Nơi sinh:");

        jLabelDanToc.setText("Dân tộc:");

        jComboBoxDanToc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelTonGiao.setText("Tôn giáo:");

        jComboBoxTonGiao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelHoTenCha.setText("Họ tên Cha:");

        jLabelNamSinhCha.setText("Năm sinh:");

        jLabelNgheNghiep.setText("Nghề Nghiệp");

        jLabelNamSinhMe.setText("Năm sinh:");

        jLabelHoTenMe.setText("Họ Tên Mẹ:");

        jLabelSdtCha.setText("Số điện thoại:");

        jButtonThemHocSinh.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButtonThemHocSinh.setText("Thêm học sinh");
        jButtonThemHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonThemHocSinhActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabelNgheNghiepMe.setText("Nghề nghiệp:");

        jLabelSdtMe.setText("Số điện thoại:");

        jLabelLop.setText("Lớp:");

        jComboBoxLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHoVaTenHS)
                                    .addComponent(jLabelGioiTinh))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonNu)
                                        .addGap(67, 67, 67))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jTextFieldHoVaTenHS))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHoTenCha)
                                    .addComponent(jLabelTonGiao))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxTonGiao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldHoTenCha)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNoiSinh)
                                    .addComponent(jLabelNgaySinh)
                                    .addComponent(jLabelDanToc))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonNam)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNoiSinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxDanToc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNgheNghiep)
                                    .addComponent(jLabelNamSinhCha))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNamSinhCha)
                                    .addComponent(jTextFieldNgheNghiep)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNamSinhMe)
                                    .addComponent(jLabelHoTenMe)
                                    .addComponent(jLabelSdtCha))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSdtCha)
                                    .addComponent(jTextFieldHoTenMe)
                                    .addComponent(jTextFieldNamSinhMe)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSdtMe)
                                    .addComponent(jLabelNgheNghiepMe))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNgheNghiepMe)
                                    .addComponent(jTextFieldSdtMe)
                                    .addComponent(jComboBoxLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jButtonThemHocSinh))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelLop)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoVaTenHS)
                    .addComponent(jTextFieldHoVaTenHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGioiTinh)
                        .addComponent(jRadioButtonNam))
                    .addComponent(jRadioButtonNu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNgaySinh)
                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoiSinh)
                    .addComponent(jTextFieldNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDanToc)
                    .addComponent(jComboBoxDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTonGiao)
                    .addComponent(jComboBoxTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoTenCha)
                    .addComponent(jTextFieldHoTenCha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamSinhCha)
                    .addComponent(jTextFieldNamSinhCha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNgheNghiep)
                    .addComponent(jTextFieldNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSdtCha)
                    .addComponent(jTextFieldSdtCha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoTenMe)
                    .addComponent(jTextFieldHoTenMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamSinhMe)
                    .addComponent(jTextFieldNamSinhMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgheNghiepMe)
                    .addComponent(jTextFieldNgheNghiepMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSdtMe)
                    .addComponent(jTextFieldSdtMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLop)
                    .addComponent(jComboBoxLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButtonThemHocSinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButtonThoat)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableDanhSachHocSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Giới tính", "Ngày sinh", "Nơi sinh", "Lớp"
            }
        ));
        jTableDanhSachHocSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDanhSachHocSinhMouseClicked(evt);
            }
        });
        danhSachHoSoHocSinh = (DefaultTableModel) jTableDanhSachHocSinh.getModel();
        jScrollPane1.setViewportView(jTableDanhSachHocSinh);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Danh sách học sinh");

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        jButtonXemChiTiet.setText("Xem chi tiết");
        jButtonXemChiTiet.setFocusable(false);
        jButtonXemChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonXemChiTiet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXemChiTietActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonXemChiTiet);

        jButtonChinhSua.setText("Chỉnh sửa");
        jButtonChinhSua.setFocusable(false);
        jButtonChinhSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonChinhSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChinhSuaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonChinhSua);

        jButtonXoa.setText("Xóa");
        jButtonXoa.setFocusable(false);
        jButtonXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonXoaActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jToolBar1.add(jButtonXoa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemHocSinhActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonThemHocSinhActionPerformed
        if (!checkJtext(jTextFieldHoVaTenHS)) return;
        newHoTen = jTextFieldHoVaTenHS.getText();

        if (jRadioButtonNam.isSelected()) newGioiTinh = "Nam";
        if (jRadioButtonNu.isSelected()) newGioiTinh = "Nữ";

        Date date = jDateChooserNgaySinh.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        newNgaySinh = dateFormat.format(date);

        if (!checkJtext(jTextFieldNoiSinh)) return;
        newNoiSinh = jTextFieldNoiSinh.getText();

        String str = "";
        String[] parts = null;

        str = (String) jComboBoxDanToc.getSelectedItem();
        parts = str.split("-");
        newDanToc_Id = Integer.parseInt(parts[0].trim());

        str = (String) jComboBoxTonGiao.getSelectedItem();
        parts = str.split("-");
        newTonGiao_Id = Integer.parseInt(parts[0].trim());

        if (!checkJtext(jTextFieldHoTenCha)) return;
        newHoTenCha = jTextFieldHoTenCha.getText();


        if (!checkNamSinh(jTextFieldNamSinhCha)) return;
        newNamSinhCha = Integer.valueOf(jTextFieldNamSinhCha.getText());

        if (!checkJtext(jTextFieldNgheNghiep)) return;
        newNgheNghiepCha = jTextFieldNgheNghiep.getText();

        if (!checkJtext(jTextFieldSdtCha)) return;
        newSoDienThoaiCha = jTextFieldSdtCha.getText();

        if (!checkJtext(jTextFieldHoTenMe)) return;
        newHoTenMe = jTextFieldHoTenMe.getText();
        if (!checkNamSinh(jTextFieldNamSinhMe)) return;
        newNamSinhMe = Integer.valueOf(jTextFieldNamSinhMe.getText());
        if (!checkJtext(jTextFieldNgheNghiepMe)) return;
        newNgheNghiepMe = jTextFieldNgheNghiepMe.getText();
        if (!checkJtext(jTextFieldSdtMe)) return;
        newSoDienThoaiMe = jTextFieldSdtMe.getText();

        str = (String) jComboBoxLop.getSelectedItem();
        parts = str.split("-");
        newLop_Id = Integer.parseInt(parts[0].trim());

        newhoSoHocSinh.setHoTen(newHoTen);
        newhoSoHocSinh.setGioiTinh(newGioiTinh);
        newhoSoHocSinh.setNgaySinh(newNgaySinh);
        newhoSoHocSinh.setNoiSinh(newNoiSinh);
        newhoSoHocSinh.setDanToc_Id(newDanToc_Id);
        newhoSoHocSinh.setTonGiao_Id(newTonGiao_Id);
        newhoSoHocSinh.setHoTenCha(newHoTenCha);
        newhoSoHocSinh.setNamSinhCha(newNamSinhCha);
        newhoSoHocSinh.setNgheNghiepCha(newNgheNghiepCha);
        newhoSoHocSinh.setSoDienThoaiCha(newSoDienThoaiCha);
        newhoSoHocSinh.setHoTenMe(newHoTenMe);
        newhoSoHocSinh.setNamSinhMe(newNamSinhMe);
        newhoSoHocSinh.setNgheNghiepMe(newNgheNghiepMe);
        newhoSoHocSinh.setSoDienThoaiMe(newSoDienThoaiMe);
        newhoSoHocSinh.setLop_Id(newLop_Id);

        hoSoHocSinhCtrl.createHoSoHocSinh(newhoSoHocSinh);
        loadDanhSachHoSoHocSinh();
    }//GEN-LAST:event_jButtonThemHocSinhActionPerformed

    private void jButtonXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemChiTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXemChiTietActionPerformed

    private void jButtonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChinhSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChinhSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonXoaActionPerformed
        hoSoHocSinhCtrl.deleteHocSinhById(idHoSoHocSinhDelete);
        loadDanhSachHoSoHocSinh();
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        dispose();
        HomeQuanLy homeQuanLy = new HomeQuanLy();
        homeQuanLy.setVisible(true);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jTableDanhSachHocSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDanhSachHocSinhMouseClicked
        int x = jTableDanhSachHocSinh.getSelectedRow();
        if (x>=0) {
            idHoSoHocSinhDelete = (int) jTableDanhSachHocSinh.getValueAt(x, 0);
        }
    }//GEN-LAST:event_jTableDanhSachHocSinhMouseClicked

    private void loadComboBox() throws SQLException {
        jComboBoxDanToc.removeAllItems();
        jComboBoxLop.removeAllItems();
        jComboBoxTonGiao.removeAllItems();

        List<DanToc> danTocs = danTocCtrl.getAllDanToc();
        for (int i = 0; i<danTocs.size(); i++){
            String str = danTocs.get(i).getId()+"-"+danTocs.get(i).getTenDanToc();
            jComboBoxDanToc.addItem(str);
        }

        List<TonGiao> tonGiaos = tonGiaoCtrl.getAllTonGiao();
        for (int i = 0; i<tonGiaos.size(); i++){
            String str = tonGiaos.get(i).getId()+"-"+tonGiaos.get(i).getTenTonGiao();
            jComboBoxTonGiao.addItem(str);
        }

        List<Lop> lops = lopCtrl.getAllLop();
        for (int i = 0; i<lops.size(); i++){
            String str = lops.get(i).getId()+"-"+lops.get(i).getTenLop();
            jComboBoxLop.addItem(str);
        }
    }

    private void loadDanhSachHoSoHocSinh() throws SQLException {
        if (danhSachHoSoHocSinh.getRowCount()>0) danhSachHoSoHocSinh.setRowCount(0);
        List<HoSoHocSinh> hoSoHocSinhs = hoSoHocSinhCtrl.getAllHoSoHocSinh();
        for (int i = 0; i<hoSoHocSinhs.size(); i++) {
            int id = hoSoHocSinhs.get(i).getId();
            String hoTen = hoSoHocSinhs.get(i).getHoTen();
            String gioiTinh = hoSoHocSinhs.get(i).getGioiTinh();
            String ngaySinh = hoSoHocSinhs.get(i).getNgaySinh();
            String noiSinh = hoSoHocSinhs.get(i).getNoiSinh();
            String lop = lopCtrl.getLopById(hoSoHocSinhs.get(i).getLop_Id()).getTenLop();

            Object[] row = {id, hoTen, gioiTinh, ngaySinh, noiSinh, lop};
            danhSachHoSoHocSinh.addRow(row);
        }
    }
    private boolean checkJtext(javax.swing.JTextField jText) {
        if (jText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Hãy nhập đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean checkNamSinh(javax.swing.JTextField jText) {
        if (!jText.getText().matches("-?\\d+(\\.\\d+)?"))
        {
            JOptionPane.showMessageDialog(null, "Năm sinh phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocSinhQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocSinhQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocSinhQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocSinhQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HocSinhQL().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonChinhSua;
    private javax.swing.JButton jButtonThemHocSinh;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXemChiTiet;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBoxDanToc;
    private javax.swing.JComboBox<String> jComboBoxLop;
    private javax.swing.JComboBox<String> jComboBoxTonGiao;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDanToc;
    private javax.swing.JLabel jLabelGioiTinh;
    private javax.swing.JLabel jLabelHoTenCha;
    private javax.swing.JLabel jLabelHoTenMe;
    private javax.swing.JLabel jLabelHoVaTenHS;
    private javax.swing.JLabel jLabelLop;
    private javax.swing.JLabel jLabelNamSinhCha;
    private javax.swing.JLabel jLabelNamSinhMe;
    private javax.swing.JLabel jLabelNgaySinh;
    private javax.swing.JLabel jLabelNgheNghiep;
    private javax.swing.JLabel jLabelNgheNghiepMe;
    private javax.swing.JLabel jLabelNoiSinh;
    private javax.swing.JLabel jLabelSdtCha;
    private javax.swing.JLabel jLabelSdtMe;
    private javax.swing.JLabel jLabelTonGiao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDanhSachHocSinh;
    private javax.swing.JTextField jTextFieldHoTenCha;
    private javax.swing.JTextField jTextFieldHoTenMe;
    private javax.swing.JTextField jTextFieldHoVaTenHS;
    private javax.swing.JTextField jTextFieldNamSinhCha;
    private javax.swing.JTextField jTextFieldNamSinhMe;
    private javax.swing.JTextField jTextFieldNgheNghiep;
    private javax.swing.JTextField jTextFieldNgheNghiepMe;
    private javax.swing.JTextField jTextFieldNoiSinh;
    private javax.swing.JTextField jTextFieldSdtCha;
    private javax.swing.JTextField jTextFieldSdtMe;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private DanTocDAO danTocDAO;
    private DanTocCtrl danTocCtrl;
    private TonGiaoDAO tonGiaoDAO;
    private TonGiaoCtrl tonGiaoCtrl;
    private LopDAO lopDAO;
    private LopCtrl lopCtrl;
    private HoSoHocSinhDAO hoSoHocSinhDAO;
    private HoSoHocSinhCtrl hoSoHocSinhCtrl;
    private HoSoHocSinh newhoSoHocSinh;
    private String newHoTen;
    private String newGioiTinh;
    private String newNgaySinh;
    private String newNoiSinh;
    private String newHoTenCha;
    private String newNgheNghiepCha;
    private String newSoDienThoaiCha;
    private String newHoTenMe;
    private String newNgheNghiepMe;
    private String newSoDienThoaiMe;
    private Integer newDanToc_Id;
    private Integer newTonGiao_Id;
    private Integer newNamSinhCha;
    private Integer newNamSinhMe;
    private Integer newLop_Id;

    private int idHoSoHocSinhDelete;
    private HoSoHocSinh suahoSoHocSinh;
    private String suaHoTen;
    private String suaGioiTinh;
    private String suaNgaySinh;
    private String suaNoiSinh;
    private String suaHoTenCha;
    private String suaNgheNghiepCha;
    private String suaSoDienThoaiCha;
    private String suaHoTenMe;
    private String suaNgheNghiepMe;
    private String suaSoDienThoaiMe;
    private Integer suaDanToc_Id;
    private Integer suaTonGiao_Id;
    private Integer suaNamSinhCha;
    private Integer suaNamSinhMe;
    private Integer suaLop_Id;

    private DefaultTableModel danhSachHoSoHocSinh;


}
