/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.QuanLy;

import com.mycompany.quanlydiemtruongthpt.Connection.MyConnection;
import com.mycompany.quanlydiemtruongthpt.UI.Auth.Login;

import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author nguyenduc
 */
public class HomeQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form HomeQuanLy
     */
    public HomeQuanLy() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneKetQuaHocTap = new javax.swing.JTabbedPane();
        jPanelQuanLy = new javax.swing.JPanel();
        jPanelLopKhoiLop = new javax.swing.JPanel();
        jButtonLopHoc = new javax.swing.JButton();
        jButtonKhoiLop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelNamHoc = new javax.swing.JPanel();
        jButtonHocKy = new javax.swing.JButton();
        jButtonNamHoc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanelMonHoc = new javax.swing.JPanel();
        jButtonMonHoc = new javax.swing.JButton();
        jButtonDiem = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanelHocSinh = new javax.swing.JPanel();
        jButtonHocSinh = new javax.swing.JButton();
        jButtonPhanLop = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanelGiaoVien = new javax.swing.JPanel();
        jButtonGiaoVien = new javax.swing.JButton();
        jButtonPhanCong = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanelKhac = new javax.swing.JPanel();
        jButtonDanToc = new javax.swing.JButton();
        jButtonTonGiao = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButtonXepLoai = new javax.swing.JButton();
        jPanelKetQuaHocTap = new javax.swing.JPanel();
        jPanelKQHK = new javax.swing.JPanel();
        jButtonKQHKL = new javax.swing.JButton();
        jLabelKQHK = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanelKQCN = new javax.swing.JPanel();
        jButtonKQCNL = new javax.swing.JButton();
        jLabelKQCN = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelthpt = new javax.swing.JLabel();
        jButtonThoat = new javax.swing.JButton();
        jButtonDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ ĐIỂM TRƯỜNG THPT");

        jTabbedPaneKetQuaHocTap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelLopKhoiLop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonLopHoc.setText("Lớp học");
        jButtonLopHoc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonLopHocActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonKhoiLop.setText("Khối lớp");
        jButtonKhoiLop.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonKhoiLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKhoiLopActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lớp - Khối lớp");

        javax.swing.GroupLayout jPanelLopKhoiLopLayout = new javax.swing.GroupLayout(jPanelLopKhoiLop);
        jPanelLopKhoiLop.setLayout(jPanelLopKhoiLopLayout);
        jPanelLopKhoiLopLayout.setHorizontalGroup(
            jPanelLopKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLopKhoiLopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLopKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jButtonLopHoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKhoiLop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLopKhoiLopLayout.setVerticalGroup(
            jPanelLopKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLopKhoiLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonKhoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNamHoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonHocKy.setText("Học kỳ");
        jButtonHocKy.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonHocKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonHocKyActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonNamHoc.setText("Năm học");
        jButtonNamHoc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonNamHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNamHocActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Năm học");

        javax.swing.GroupLayout jPanelNamHocLayout = new javax.swing.GroupLayout(jPanelNamHoc);
        jPanelNamHoc.setLayout(jPanelNamHocLayout);
        jPanelNamHocLayout.setHorizontalGroup(
            jPanelNamHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNamHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNamHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanelNamHocLayout.createSequentialGroup()
                        .addGroup(jPanelNamHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelNamHocLayout.setVerticalGroup(
            jPanelNamHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNamHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMonHoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonMonHoc.setText("Môn học");
        jButtonMonHoc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonMonHocActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonDiem.setText("Điểm");
        jButtonDiem.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiemActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Môn học");

        javax.swing.GroupLayout jPanelMonHocLayout = new javax.swing.GroupLayout(jPanelMonHoc);
        jPanelMonHoc.setLayout(jPanelMonHocLayout);
        jPanelMonHocLayout.setHorizontalGroup(
            jPanelMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMonHocLayout.createSequentialGroup()
                        .addGroup(jPanelMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanelMonHocLayout.createSequentialGroup()
                        .addGroup(jPanelMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanelMonHocLayout.setVerticalGroup(
            jPanelMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelHocSinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonHocSinh.setText("Học sinh");
        jButtonHocSinh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonHocSinhActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonPhanLop.setText("Phân lớp");
        jButtonPhanLop.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonPhanLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonPhanLopActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Học sinh");

        javax.swing.GroupLayout jPanelHocSinhLayout = new javax.swing.GroupLayout(jPanelHocSinh);
        jPanelHocSinh.setLayout(jPanelHocSinhLayout);
        jPanelHocSinhLayout.setHorizontalGroup(
            jPanelHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHocSinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHocSinhLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelHocSinhLayout.createSequentialGroup()
                        .addGroup(jPanelHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPhanLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4))
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        jPanelHocSinhLayout.setVerticalGroup(
            jPanelHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHocSinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPhanLop, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelGiaoVien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonGiaoVien.setText("Giáo viên");
        jButtonGiaoVien.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonGiaoVienActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonPhanCong.setText("Phân công");
        jButtonPhanCong.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonPhanCongActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Giáo viên");

        javax.swing.GroupLayout jPanelGiaoVienLayout = new javax.swing.GroupLayout(jPanelGiaoVien);
        jPanelGiaoVien.setLayout(jPanelGiaoVienLayout);
        jPanelGiaoVienLayout.setHorizontalGroup(
            jPanelGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGiaoVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGiaoVienLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelGiaoVienLayout.createSequentialGroup()
                        .addGroup(jPanelGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPhanCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        jPanelGiaoVienLayout.setVerticalGroup(
            jPanelGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGiaoVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelKhac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonDanToc.setText("Dân tộc");
        jButtonDanToc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonDanToc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDanTocActionPerformed(evt);
            }
        });

        jButtonTonGiao.setText("Tôn giáo");
        jButtonTonGiao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonTonGiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTonGiaoActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Khác");

        jButtonXepLoai.setText("Xếp loại");
        jButtonXepLoai.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonXepLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXepLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelKhacLayout = new javax.swing.GroupLayout(jPanelKhac);
        jPanelKhac.setLayout(jPanelKhacLayout);
        jPanelKhacLayout.setHorizontalGroup(
            jPanelKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDanToc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonXepLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTonGiao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelKhacLayout.setVerticalGroup(
            jPanelKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDanToc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTonGiao)
                .addGroup(jPanelKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKhacLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKhacLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonXepLoai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelQuanLyLayout = new javax.swing.GroupLayout(jPanelQuanLy);
        jPanelQuanLy.setLayout(jPanelQuanLyLayout);
        jPanelQuanLyLayout.setHorizontalGroup(
            jPanelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLopKhoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanelQuanLyLayout.setVerticalGroup(
            jPanelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelKhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNamHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLopKhoiLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPaneKetQuaHocTap.addTab("Quản lý", jPanelQuanLy);

        jPanelKQHK.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonKQHKL.setText("Kết quả học kỳ");
        jButtonKQHKL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonKQHKL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonKQHKLActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabelKQHK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKQHK.setText("Kết quả học kỳ");

        javax.swing.GroupLayout jPanelKQHKLayout = new javax.swing.GroupLayout(jPanelKQHK);
        jPanelKQHK.setLayout(jPanelKQHKLayout);
        jPanelKQHKLayout.setHorizontalGroup(
            jPanelKQHKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKQHKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKQHKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator7)
                    .addComponent(jButtonKQHKL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jLabelKQHK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelKQHKLayout.setVerticalGroup(
            jPanelKQHKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKQHKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonKQHKL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKQHK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelKQCN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonKQCNL.setText("Kết quả cả năm");
        jButtonKQCNL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonKQCNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonKQCNLActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabelKQCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKQCN.setText("Kết quả cả năm");

        javax.swing.GroupLayout jPanelKQCNLayout = new javax.swing.GroupLayout(jPanelKQCN);
        jPanelKQCN.setLayout(jPanelKQCNLayout);
        jPanelKQCNLayout.setHorizontalGroup(
            jPanelKQCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKQCNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKQCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator8)
                    .addComponent(jButtonKQCNL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jLabelKQCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKQCNLayout.setVerticalGroup(
            jPanelKQCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKQCNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonKQCNL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKQCN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelKetQuaHocTapLayout = new javax.swing.GroupLayout(jPanelKetQuaHocTap);
        jPanelKetQuaHocTap.setLayout(jPanelKetQuaHocTapLayout);
        jPanelKetQuaHocTapLayout.setHorizontalGroup(
            jPanelKetQuaHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKetQuaHocTapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelKQHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelKQCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanelKetQuaHocTapLayout.setVerticalGroup(
            jPanelKetQuaHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKetQuaHocTapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKetQuaHocTapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelKQHK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKQCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneKetQuaHocTap.addTab("Kết quả học tập", jPanelKetQuaHocTap);

        jLabelthpt.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabelthpt.setForeground(new java.awt.Color(255, 0, 0));
        jLabelthpt.setText("TRƯỜNG THPT TIÊN HƯNG");

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jButtonDangXuat.setText("Đăng xuất");
        jButtonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonDangXuatActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDangXuat)
                .addGap(18, 18, 18)
                .addComponent(jButtonThoat))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabelthpt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabelthpt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThoat)
                    .addComponent(jButtonDangXuat))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneKetQuaHocTap)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneKetQuaHocTap, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonXepLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXepLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXepLoaiActionPerformed

    private void jButtonTonGiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTonGiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTonGiaoActionPerformed

    private void jButtonDanTocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDanTocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDanTocActionPerformed

    private void jButtonPhanCongActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPhanCongActionPerformed
        dispose();
        PhanCongQL phanCongQL = new PhanCongQL();
        phanCongQL.setVisible(true);
    }//GEN-LAST:event_jButtonPhanCongActionPerformed

    private void jButtonGiaoVienActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonGiaoVienActionPerformed
        dispose();
        GiaoVienQL giaoVienQL = new GiaoVienQL();
        giaoVienQL.setVisible(true);
    }//GEN-LAST:event_jButtonGiaoVienActionPerformed

    private void jButtonPhanLopActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPhanLopActionPerformed
        dispose();
        PhanLopQL phanLopQL = new PhanLopQL();
        phanLopQL.setVisible(true);
    }//GEN-LAST:event_jButtonPhanLopActionPerformed

    private void jButtonHocSinhActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonHocSinhActionPerformed
        dispose();
        HocSinhQL hocSinhQL = new HocSinhQL();
        hocSinhQL.setVisible(true);
    }//GEN-LAST:event_jButtonHocSinhActionPerformed

    private void jButtonDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDiemActionPerformed

    private void jButtonMonHocActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonMonHocActionPerformed
        dispose();
        MonHocQL monHocQL = new MonHocQL();
        monHocQL.setVisible(true);
    }//GEN-LAST:event_jButtonMonHocActionPerformed

    private void jButtonNamHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNamHocActionPerformed

    }//GEN-LAST:event_jButtonNamHocActionPerformed

    private void jButtonHocKyActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonHocKyActionPerformed
        dispose();
        HocKyQL hocKyQL = new HocKyQL();
        hocKyQL.setVisible(true);
    }//GEN-LAST:event_jButtonHocKyActionPerformed

    private void jButtonKhoiLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKhoiLopActionPerformed

    }//GEN-LAST:event_jButtonKhoiLopActionPerformed

    private void jButtonLopHocActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonLopHocActionPerformed
        dispose();
        LopHocQL lopHocQL = new LopHocQL();
        lopHocQL.setVisible(true);
    }//GEN-LAST:event_jButtonLopHocActionPerformed

    private void jButtonKQHKLActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonKQHKLActionPerformed
        KetQuaHocKy ketQuaHocKy = new KetQuaHocKy();
        ketQuaHocKy.setVisible(true);
    }//GEN-LAST:event_jButtonKQHKLActionPerformed

    private void jButtonKQCNLActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonKQCNLActionPerformed
        KetQuaNamHoc ketQuaNamHoc = new KetQuaNamHoc();
        ketQuaNamHoc.setVisible(true);
    }//GEN-LAST:event_jButtonKQCNLActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonDangXuatActionPerformed(ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonDangXuatActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDanToc;
    private javax.swing.JButton jButtonDangXuat;
    private javax.swing.JButton jButtonDiem;
    private javax.swing.JButton jButtonGiaoVien;
    private javax.swing.JButton jButtonHocKy;
    private javax.swing.JButton jButtonHocSinh;
    private javax.swing.JButton jButtonKQCNL;
    private javax.swing.JButton jButtonKQHKL;
    private javax.swing.JButton jButtonKhoiLop;
    private javax.swing.JButton jButtonLopHoc;
    private javax.swing.JButton jButtonMonHoc;
    private javax.swing.JButton jButtonNamHoc;
    private javax.swing.JButton jButtonPhanCong;
    private javax.swing.JButton jButtonPhanLop;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonTonGiao;
    private javax.swing.JButton jButtonXepLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelKQCN;
    private javax.swing.JLabel jLabelKQHK;
    private javax.swing.JLabel jLabelthpt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGiaoVien;
    private javax.swing.JPanel jPanelHocSinh;
    private javax.swing.JPanel jPanelKQCN;
    private javax.swing.JPanel jPanelKQHK;
    private javax.swing.JPanel jPanelKetQuaHocTap;
    private javax.swing.JPanel jPanelKhac;
    private javax.swing.JPanel jPanelLopKhoiLop;
    private javax.swing.JPanel jPanelMonHoc;
    private javax.swing.JPanel jPanelNamHoc;
    private javax.swing.JPanel jPanelQuanLy;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPaneKetQuaHocTap;
    // End of variables declaration//GEN-END:variables
}
