/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.QuanLy;

import com.mycompany.quanlydiemtruongthpt.Controller.HocKyCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.LopCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.NamHocCtrl;
import com.mycompany.quanlydiemtruongthpt.Model.HocKy;
import com.mycompany.quanlydiemtruongthpt.Model.Lop;
import com.mycompany.quanlydiemtruongthpt.Model.NamHoc;

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class KetQuaNamHoc extends javax.swing.JFrame {

    /**
     * Creates new form KetQuaNamHoc
     */
    public KetQuaNamHoc() throws SQLException {
        lopCtrl = new LopCtrl();
        namHocCtrl = new NamHocCtrl();
        initComponents();
        loadComboBox();
        loadDanhSach();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxLopHoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxNamHoc = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));

        danhSach= (DefaultTableModel) jTable1.getModel();
        loadComboBox();
        loadTenCot();
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Lớp học:");

        jComboBoxLopHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Năm học:");

        jComboBoxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Xem kết quả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton1ActionPerformed
        loadDanhSach();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadComboBox() throws SQLException {
        List<Lop> lops = lopCtrl.getAllLop();
        List<NamHoc> namHocs = namHocCtrl.getAllNamHoc();

        jComboBoxLopHoc.removeAllItems();
        jComboBoxNamHoc.removeAllItems();

        for (int i = 0; i<lops.size(); i++) {
            jComboBoxLopHoc.addItem(lops.get(i).getId()+"-"+lops.get(i).getTenLop());
        }

        for (int i = 0; i<namHocs.size(); i++) {
            jComboBoxNamHoc.addItem(namHocs.get(i).getId()+"-"+namHocs.get(i).getTenNamHoc());
        }
    }

    private void loadTenCot() throws SQLException {
        danhSach.addColumn("ID");
        danhSach.addColumn("Họ tên");
        danhSach.addColumn("Giới tính");
        danhSach.addColumn("Ngày sinh");

        String str = (String) jComboBoxNamHoc.getSelectedItem();
        String[] parts = str.split("-");
        int idNamHoc = Integer.parseInt(parts[0].trim());
        List<HocKy> hocKys = new HocKyCtrl().getHocKyByIdNamHoc(idNamHoc);
        for (int i = 0; i<hocKys.size(); i++) {
            danhSach.addColumn(hocKys.get(i).getTenHocKy());
        }

        danhSach.addColumn("Điểm trung bình năm học");
        danhSach.addColumn("Hạnh kiểm");
        danhSach.addColumn("Học lực");
        danhSach.addColumn("Kết quả");
    }

    private void loadDanhSach() throws SQLException {
        if (danhSach.getRowCount()>0) danhSach.setRowCount(0);

        String strLop = (String) jComboBoxLopHoc.getSelectedItem();
        String[] parts = strLop.split("-");
        int idLop = Integer.parseInt(parts[0].trim());

        String strNamHoc = (String) jComboBoxNamHoc.getSelectedItem();
        String[] parts2 = strNamHoc.split("-");
        int idNamHoc = Integer.parseInt(parts2[0].trim());

        ResultSet resultSet = lopCtrl.getKetQuaTheoNamHoc(idLop, idNamHoc);

        while (resultSet.next()) {
            int idHocSinh = resultSet.getInt("HocSinh_Id");
            String hoTen = resultSet.getString("HoTen");
            String gioiTinh = resultSet.getString("GioiTinh");
            String ngaySinh = resultSet.getString("NgaySinh");

            Object[] row = {idHocSinh,hoTen, gioiTinh, ngaySinh};
            List<HocKy> hocKys = new HocKyCtrl().getHocKyByIdNamHoc(idNamHoc);
            for (int i = 0; i<hocKys.size(); i++) {
                row = Arrays.copyOf(row, row.length+1);
                row[row.length-1] = resultSet.getFloat(hocKys.get(i).getTenHocKy());

            }
            row = Arrays.copyOf(row, row.length+1);
            row[row.length-1] = resultSet.getFloat("DiemTrungBinhCaNam");

            row = Arrays.copyOf(row, row.length+1);
            row[row.length-1] = resultSet.getString("TenHanhKiem");
            row = Arrays.copyOf(row, row.length+1);
            row[row.length-1] = resultSet.getString("TenHocLuc");
            row = Arrays.copyOf(row, row.length+1);
            row[row.length-1] = resultSet.getString("TenKetQua");

            danhSach.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetQuaNamHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetQuaNamHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetQuaNamHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetQuaNamHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KetQuaNamHoc().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxLopHoc;
    private javax.swing.JComboBox<String> jComboBoxNamHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private LopCtrl lopCtrl;
    private NamHocCtrl namHocCtrl;
    private DefaultTableModel danhSach;

}
