/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.QuanLy;

import com.mycompany.quanlydiemtruongthpt.Controller.GiaoVienCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.KhoiLopCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.LopCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.NamHocCtrl;
import com.mycompany.quanlydiemtruongthpt.DAO.LopDAO;
import com.mycompany.quanlydiemtruongthpt.Model.GiaoVien;
import com.mycompany.quanlydiemtruongthpt.Model.KhoiLop;
import com.mycompany.quanlydiemtruongthpt.Model.Lop;
import com.mycompany.quanlydiemtruongthpt.Model.NamHoc;

import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class LopHocQL extends javax.swing.JFrame {

    /**
     * Creates new form LopHocQL
     */
    public LopHocQL() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        loadDanhSach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lopCtrl = new LopCtrl();
        khoiLopCtrl = new KhoiLopCtrl();
        giaoVienCtrl = new GiaoVienCtrl();
        namHocCtrl = new NamHocCtrl();
        lopNew = new Lop();
        lopSua = new Lop();

        jPanel2 = new javax.swing.JPanel();
        jButtonDanhSach = new javax.swing.JButton();
        jButtonThemLop = new javax.swing.JButton();
        jButtonThemKhoiLop = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelDanhSachCacLop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonXemDanhSachHocSinh = new javax.swing.JButton();
        jPanelThemLop = new javax.swing.JPanel();
        jLabelTenLop = new javax.swing.JLabel();
        jTextFieldTenLop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxKhoiLop = new javax.swing.JComboBox<>();
        jLabelNamHoc = new javax.swing.JLabel();
        jComboBoxNamHoc = new javax.swing.JComboBox<>();
        jLabelGiaoVien = new javax.swing.JLabel();
        jComboBoxGiaoVien = new javax.swing.JComboBox<>();
        jButtonThem = new javax.swing.JButton();
        jPanelSua = new javax.swing.JPanel();
        jLabelTenLop1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNamHoc1 = new javax.swing.JLabel();
        jLabelGiaoVien1 = new javax.swing.JLabel();
        jComboBoxGiaoVienSua = new javax.swing.JComboBox<>();
        jComboBoxNamHocSua = new javax.swing.JComboBox<>();
        jComboBoxKhoiLopSua = new javax.swing.JComboBox<>();
        jTextFieldTenLopSua = new javax.swing.JTextField();
        jButtonHoanTat = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jPanelThemKhoiLop = new javax.swing.JPanel();
        jLabelDanhSachKhoiLop = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabeTenKhoiLop = new javax.swing.JLabel();
        jTextFieldTenKhoiLop = new javax.swing.JTextField();
        jButtonThemKhoiLopNew = new javax.swing.JButton();
        jButtonSuaKhoiLop = new javax.swing.JButton();
        jButtonXoaKhoiLop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ LỚP HỌC");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonDanhSach.setText("Danh sách các lớp");
        jButtonDanhSach.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonDanhSachActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThemLop.setText("Thêm lớp");
        jButtonThemLop.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonThemLopActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThemKhoiLop.setText("Thêm khối lớp");
        jButtonThemKhoiLop.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonThemKhoiLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonThemKhoiLopActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonThemLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonThemKhoiLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonThoat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThemKhoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonThoat)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "ID", "Lớp","Khối lớp", "Giáo Viên", "Năm Học"
            }
        ));
        danhSachLopHoc = (DefaultTableModel) jTable1.getModel();

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTable1MouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonXoaActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonXemDanhSachHocSinh.setText("Xem danh sách học sinh");
        jButtonXemDanhSachHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonXemDanhSachHocSinhActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanelDanhSachCacLopLayout = new javax.swing.GroupLayout(jPanelDanhSachCacLop);
        jPanelDanhSachCacLop.setLayout(jPanelDanhSachCacLopLayout);
        jPanelDanhSachCacLopLayout.setHorizontalGroup(
            jPanelDanhSachCacLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachCacLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDanhSachCacLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDanhSachCacLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonSua)
                        .addComponent(jButtonXoa))
                    .addComponent(jButtonXemDanhSachHocSinh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDanhSachCacLopLayout.setVerticalGroup(
            jPanelDanhSachCacLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachCacLopLayout.createSequentialGroup()
                .addGroup(jPanelDanhSachCacLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDanhSachCacLopLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonXoa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXemDanhSachHocSinh))
                    .addGroup(jPanelDanhSachCacLopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelDanhSachCacLop, "DanhSachCacLopCard");
        jPanelDanhSachCacLop.getAccessibleContext().setAccessibleName("DanhSachCacLop");

        jLabelTenLop.setText("Tên lớp:");

        jLabel1.setText("Khối lớp:");

        jComboBoxKhoiLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabelNamHoc.setText("Năm học:");

        jComboBoxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabelGiaoVien.setText("GVCN");

        jComboBoxGiaoVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonThemActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanelThemLopLayout = new javax.swing.GroupLayout(jPanelThemLop);
        jPanelThemLop.setLayout(jPanelThemLopLayout);
        jPanelThemLopLayout.setHorizontalGroup(
            jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemLopLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTenLop)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNamHoc)
                    .addComponent(jLabelGiaoVien))
                .addGap(32, 32, 32)
                .addGroup(jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonThem)
                    .addGroup(jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldTenLop)
                        .addComponent(jComboBoxKhoiLop, 0, 316, Short.MAX_VALUE)
                        .addComponent(jComboBoxNamHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxGiaoVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanelThemLopLayout.setVerticalGroup(
            jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemLopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenLop)
                    .addComponent(jTextFieldTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxKhoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamHoc)
                    .addComponent(jComboBoxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGiaoVien)
                    .addComponent(jComboBoxGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonThem)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelThemLop, "ThemLopCard");

        jLabelTenLop1.setText("Tên lớp:");

        jLabel2.setText("Khối lớp:");

        jLabelNamHoc1.setText("Năm học:");

        jLabelGiaoVien1.setText("GVCN:");

        jComboBoxGiaoVienSua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jComboBoxNamHocSua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jComboBoxKhoiLopSua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jButtonHoanTat.setText("Hoàn tất");
        jButtonHoanTat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHoanTatActionPerformed(evt);
            }
        });

        jButtonHuy.setText("Hủy");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuaLayout = new javax.swing.GroupLayout(jPanelSua);
        jPanelSua.setLayout(jPanelSuaLayout);
        jPanelSuaLayout.setHorizontalGroup(
            jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTenLop1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNamHoc1)
                    .addComponent(jLabelGiaoVien1))
                .addGap(32, 32, 32)
                .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuaLayout.createSequentialGroup()
                        .addComponent(jButtonHoanTat)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonHuy))
                    .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldTenLopSua)
                        .addComponent(jComboBoxKhoiLopSua, 0, 316, Short.MAX_VALUE)
                        .addComponent(jComboBoxNamHocSua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxGiaoVienSua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanelSuaLayout.setVerticalGroup(
            jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenLop1)
                    .addComponent(jTextFieldTenLopSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxKhoiLopSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamHoc1)
                    .addComponent(jComboBoxNamHocSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGiaoVien1)
                    .addComponent(jComboBoxGiaoVienSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHoanTat)
                    .addComponent(jButtonHuy))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelSua, "SuaCard");

        jLabelDanhSachKhoiLop.setText("Danh sách khối lớp:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "ID", "Khối"
            }
        ));
        jTable2.setCellSelectionEnabled(true);
        danhSachKhoiLopHoc = (DefaultTableModel) jTable2.getModel();
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTable2MouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabeTenKhoiLop.setText("Tên Khối Lớp:");

        jButtonThemKhoiLopNew.setText("Thêm Khối Lớp");
        jButtonThemKhoiLopNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonThemKhoiLopNewActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonSuaKhoiLop.setText("Sửa");

        jButtonXoaKhoiLop.setText("Xóa");
        jButtonXoaKhoiLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonXoaKhoiLopActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanelThemKhoiLopLayout = new javax.swing.GroupLayout(jPanelThemKhoiLop);
        jPanelThemKhoiLop.setLayout(jPanelThemKhoiLopLayout);
        jPanelThemKhoiLopLayout.setHorizontalGroup(
            jPanelThemKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemKhoiLopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelThemKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelThemKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelThemKhoiLopLayout.createSequentialGroup()
                            .addComponent(jLabeTenKhoiLop)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTenKhoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addComponent(jButtonThemKhoiLopNew)
                        .addComponent(jLabelDanhSachKhoiLop)
                        .addGroup(jPanelThemKhoiLopLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addGroup(jPanelThemKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSuaKhoiLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonXoaKhoiLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanelThemKhoiLopLayout.setVerticalGroup(
            jPanelThemKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemKhoiLopLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelDanhSachKhoiLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThemKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemKhoiLopLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelThemKhoiLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeTenKhoiLop)
                            .addComponent(jTextFieldTenKhoiLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonThemKhoiLopNew))
                    .addGroup(jPanelThemKhoiLopLayout.createSequentialGroup()
                        .addComponent(jButtonSuaKhoiLop)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoaKhoiLop)))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelThemKhoiLop, "ThemKhoiLopCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void removeJComboBox () {
        jComboBoxGiaoVien.removeAllItems();
        jComboBoxNamHoc.removeAllItems();
        jComboBoxNamHocSua.removeAllItems();
        jComboBoxKhoiLop.removeAllItems();
        jComboBoxGiaoVienSua.removeAllItems();

    }
    private void loadDanhSach() throws SQLException {
        removeJComboBox();

        List<KhoiLop> khoiLops = khoiLopCtrl.getAllKhoiLop();
        for (int i = 0; i < khoiLops.size(); i++) {
            String str = khoiLops.get(i).getId()+"-"+khoiLops.get(i).getTenKhoiLop();
            jComboBoxKhoiLop.addItem(str);
            jComboBoxKhoiLopSua.addItem(str);
        }

        List<GiaoVien> giaoViens = giaoVienCtrl.getListGiaoVienKhongLaChuNhiem();
        for (int i = 0; i<giaoViens.size(); i++) {
            String str = giaoViens.get(i).getId()+"-"+giaoViens.get(i).getHoTen();
            jComboBoxGiaoVien.addItem(str);
            jComboBoxGiaoVienSua.addItem(str);
        }

        List<NamHoc> namHocs = namHocCtrl.getAllNamHoc();
        for (int i = 0; i<namHocs.size(); i++) {
            String str = namHocs.get(i).getId()+"-"+ namHocs.get(i).getTenNamHoc();
            jComboBoxNamHoc.addItem(str);
            jComboBoxNamHocSua.addItem(str);
        }
        List<Lop> lops = lopCtrl.getAllLop();
        if (lops.size() > 0) {
            if (danhSachLopHoc.getRowCount() > 0) {
                danhSachLopHoc.setRowCount(0);
            }
            for (int i = 0; i< lops.size(); i++) {
                Integer id = lops.get(i).getId();
                String tenLop = lops.get(i).getTenLop();
                String tenKhoiLop = lops.get(i).getKhoiLop_Id()+"-"+khoiLopCtrl.getKhoiLopById(lops.get(i).getKhoiLop_Id()).getTenKhoiLop();
                String tenGiaoVien = lops.get(i).getGiaoVien_Id()+"-"+ giaoVienCtrl.getGiaoVienById(lops.get(i).getGiaoVien_Id()).getHoTen();
                String tenNamHoc = lops.get(i).getNamHoc_Id()+"-"+ namHocCtrl.getNamHocById(lops.get(0).getNamHoc_Id()).getTenNamHoc();
                Object[] row = {id, tenLop, tenKhoiLop, tenGiaoVien, tenNamHoc};
                danhSachLopHoc.addRow(row);
            }
        }
    }

    private void loadDanhSachKhoiLopHoc() throws SQLException {
        removeJComboBox();
        List<KhoiLop> khoiLops = khoiLopCtrl.getAllKhoiLop();
        for (int i = 0; i < khoiLops.size(); i++) {
            String str = khoiLops.get(i).getId()+"-"+khoiLops.get(i).getTenKhoiLop();
            jComboBoxKhoiLop.addItem(str);
            jComboBoxKhoiLopSua.addItem(str);
        }
        if (khoiLops.size() > 0) {
            if (danhSachKhoiLopHoc.getRowCount() > 0) {
                danhSachKhoiLopHoc.setRowCount(0);
            }
            for (int i = 0; i< khoiLops.size(); i++) {
                Integer id = khoiLops.get(i).getId();
                String tenKhoiLop = khoiLops.get(i).getTenKhoiLop();

                Object[] row = {id, tenKhoiLop};
                danhSachKhoiLopHoc.addRow(row);
            }
        }
    }

    private void jButtonDanhSachActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonDanhSachActionPerformed
        showPanel("DanhSachCacLopCard");
        this.loadDanhSach();
    }//GEN-LAST:event_jButtonDanhSachActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        jTextFieldTenLopSua.setText(suaTenLop);

        showPanel("SuaCard");
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonXoaActionPerformed
        lopCtrl.deleteLopById(IdLopDelete);
        loadDanhSach();
    }//GEN-LAST:event_jButtonXoaActionPerformed
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) throws SQLException {
        int x = jTable1.getSelectedRow();
        if (x>=0) {
            String str = "";
            String[] parts = null;
            IdLopDelete = (int) jTable1.getValueAt(x, 0);
            idLopDanhSach = IdLopDelete;
            //tên lớp
            suaTenLop = (String) jTable1.getValueAt(x, 1);

            // id khối lớp
            str = (String) jTable1.getValueAt(x, 2);
            parts = str.split("-");
            suaKhoiLop = Integer.parseInt(parts[0].trim());

            // Nam hoc
            str = (String) jTable1.getValueAt(x, 3);
            parts = str.split("-");
            suaNamHoc = Integer.parseInt(parts[0].trim());

            // Giao vien
            str = (String) jTable1.getValueAt(x, 4);
            parts = str.split("-");
            suaGiaoVien = Integer.parseInt(parts[0].trim());
        }
    }
    private void jButtonXoaKhoiLopActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        khoiLopCtrl.deleteKhoiLopById(idKhoiLopDelete);
        loadDanhSachKhoiLopHoc();
    }
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) throws SQLException {
        int x = jTable2.getSelectedRow();
        if (x>=0) {
            idKhoiLopDelete = (int) jTable2.getValueAt(x, 0);
        }
    }
    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonThemActionPerformed
        String str = "";
        String[] parts = null;
        //tên lớp
        tmpTenLop =  jTextFieldTenLop.getText();

        // id khối lớp
        str = (String) jComboBoxKhoiLop.getSelectedItem();
        parts = str.split("-");
        tmpKhoiLop = Integer.parseInt(parts[0].trim());

        // Nam hoc
        str = (String) jComboBoxNamHoc.getSelectedItem();
        parts = str.split("-");
        tmpNamHoc = Integer.parseInt(parts[0].trim());

        // Giao vien
        str = (String) jComboBoxGiaoVien.getSelectedItem();
        parts = str.split("-");
        tmpGiaoVien = Integer.parseInt(parts[0].trim());


        lopNew.setTenLop(tmpTenLop);
        lopNew.setKhoiLop_Id(tmpKhoiLop);
        lopNew.setGiaoVien_Id(tmpGiaoVien);
        lopNew.setNamHoc_Id(tmpNamHoc);

        lopCtrl.createLop(lopNew);
        loadDanhSach();
        showPanel("DanhSachCacLopCard");
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonHoanTatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHoanTatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHoanTatActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        showPanel("DanhSachCacLopCard");
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jButtonThemLopActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonThemLopActionPerformed
        showPanel("ThemLopCard");
        loadDanhSach();
    }//GEN-LAST:event_jButtonThemLopActionPerformed

    private void jButtonThemKhoiLopNewActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonThemKhoiLopNewActionPerformed
        String TenKhoiLop = jTextFieldTenKhoiLop.getText();
        KhoiLop khoiLop = new KhoiLop(TenKhoiLop);
        khoiLopCtrl.createKhoiLop(khoiLop);
        loadDanhSachKhoiLopHoc();
    }//GEN-LAST:event_jButtonThemKhoiLopNewActionPerformed

    private void jButtonThemKhoiLopActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonThemKhoiLopActionPerformed
        showPanel("ThemKhoiLopCard");
        loadDanhSachKhoiLopHoc();
    }//GEN-LAST:event_jButtonThemKhoiLopActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        dispose();
        HomeQuanLy homeQuanLy = new HomeQuanLy();
        homeQuanLy.setVisible(true);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonXemDanhSachHocSinhActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonXemDanhSachHocSinhActionPerformed
        DanhSachHocSinh danhSachHocSinh = new DanhSachHocSinh(idLopDanhSach);
        danhSachHocSinh.setVisible(true);
    }//GEN-LAST:event_jButtonXemDanhSachHocSinhActionPerformed
    private void showPanel(String panelName) {

        CardLayout layout = (CardLayout) jPanel3.getLayout();
        layout.show(jPanel3, panelName);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LopHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LopHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LopHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LopHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LopHocQL().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDanhSach;
    private javax.swing.JButton jButtonHoanTat;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonSuaKhoiLop;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThemKhoiLop;
    private javax.swing.JButton jButtonThemKhoiLopNew;
    private javax.swing.JButton jButtonThemLop;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXemDanhSachHocSinh;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonXoaKhoiLop;
    private javax.swing.JComboBox<String> jComboBoxGiaoVien;
    private javax.swing.JComboBox<String> jComboBoxGiaoVienSua;
    private javax.swing.JComboBox<String> jComboBoxKhoiLop;
    private javax.swing.JComboBox<String> jComboBoxKhoiLopSua;
    private javax.swing.JComboBox<String> jComboBoxNamHoc;
    private javax.swing.JComboBox<String> jComboBoxNamHocSua;
    private javax.swing.JLabel jLabeTenKhoiLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDanhSachKhoiLop;
    private javax.swing.JLabel jLabelGiaoVien;
    private javax.swing.JLabel jLabelGiaoVien1;
    private javax.swing.JLabel jLabelNamHoc;
    private javax.swing.JLabel jLabelNamHoc1;
    private javax.swing.JLabel jLabelTenLop;
    private javax.swing.JLabel jLabelTenLop1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDanhSachCacLop;
    private javax.swing.JPanel jPanelSua;
    private javax.swing.JPanel jPanelThemKhoiLop;
    private javax.swing.JPanel jPanelThemLop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldTenKhoiLop;
    private javax.swing.JTextField jTextFieldTenLop;
    private javax.swing.JTextField jTextFieldTenLopSua;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel danhSachLopHoc;
    private DefaultTableModel danhSachKhoiLopHoc;
    private LopCtrl lopCtrl;
    private KhoiLopCtrl khoiLopCtrl;
    private NamHocCtrl namHocCtrl;
    private GiaoVienCtrl giaoVienCtrl;
    private Lop lopNew;
    private Lop lopSua;
    private String tmpTenLop;
    private int tmpKhoiLop;
    private int tmpNamHoc;
    private int tmpGiaoVien;
    private int IdLopDelete;
    private String suaTenLop;
    private int suaKhoiLop;
    private int suaNamHoc;
    private int suaGiaoVien;

    private int idKhoiLopDelete;
    private int idLopDanhSach;
}
