/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.QuanLy;

import com.mycompany.quanlydiemtruongthpt.Controller.MonHocCtrl;
import com.mycompany.quanlydiemtruongthpt.DAO.MonHocDAO;
import com.mycompany.quanlydiemtruongthpt.Model.MonHoc;

import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class MonHocQL extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public MonHocQL() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        loadDanhSachMonHoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        monHocDAO = new MonHocDAO();
        monHocCtrl = new MonHocCtrl();
        newMonHoc = new MonHoc();
        suaMonHoc = new MonHoc();
        jPanel1 = new javax.swing.JPanel();
        jPanelDanhSachMonHoc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelDanhSachMonHoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachMonHoc = new javax.swing.JTable();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelThemMonHoc = new javax.swing.JLabel();
        jLabelTenMonHoc = new javax.swing.JLabel();
        jTextFieldTenMonHoc = new javax.swing.JTextField();
        jLabelSoTiet = new javax.swing.JLabel();
        jTextFieldSoTiet = new javax.swing.JTextField();
        jLabelHeSo = new javax.swing.JLabel();
        jTextFieldHeSo = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTenMonHocSua = new javax.swing.JLabel();
        jTextFieldTenMonHocSua = new javax.swing.JTextField();
        jLabelSoTietSua = new javax.swing.JLabel();
        jTextFieldSoTietSua = new javax.swing.JTextField();
        jLabelHeSoSua = new javax.swing.JLabel();
        jTextFieldHeSoSua = new javax.swing.JTextField();
        jButtonCapNhat = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ MÔN HỌC");

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDanhSachMonHoc.setText("Danh sách môn học:");

        jTableDanhSachMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên môn học", "Số tiết", "Hệ số"
            }
        ));
        danhSachMonHoc = (DefaultTableModel) jTableDanhSachMonHoc.getModel();
        jTableDanhSachMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDanhSachMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDanhSachMonHoc);

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonXoaActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSua)
                            .addComponent(jButtonXoa)))
                    .addComponent(jLabelDanhSachMonHoc))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDanhSachMonHoc)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonSua)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelThemMonHoc.setText("Thêm môn học:");

        jLabelTenMonHoc.setText("Tên môn học:");

        jLabelSoTiet.setText("Số tiết:");

        jLabelHeSo.setText("Hệ số:");

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonThemActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTenMonHoc)
                            .addComponent(jLabelSoTiet)
                            .addComponent(jLabelHeSo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHeSo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTextFieldSoTiet)
                            .addComponent(jTextFieldTenMonHoc)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonThem)
                            .addComponent(jLabelThemMonHoc))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelThemMonHoc)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenMonHoc)
                    .addComponent(jTextFieldTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSoTiet)
                    .addComponent(jTextFieldSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHeSo)
                    .addComponent(jTextFieldHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonThem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDanhSachMonHocLayout = new javax.swing.GroupLayout(jPanelDanhSachMonHoc);
        jPanelDanhSachMonHoc.setLayout(jPanelDanhSachMonHocLayout);
        jPanelDanhSachMonHocLayout.setHorizontalGroup(
            jPanelDanhSachMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDanhSachMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDanhSachMonHocLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDanhSachMonHocLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonThoat)))
                .addContainerGap())
        );
        jPanelDanhSachMonHocLayout.setVerticalGroup(
            jPanelDanhSachMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachMonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDanhSachMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonThoat)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelDanhSachMonHoc, "DanhSachMonHocCard");

        jLabelTenMonHocSua.setText("Tên môn học:");

        jLabelSoTietSua.setText("Số tiết:");

        jLabelHeSoSua.setText("Hệ số:");

        jButtonCapNhat.setText("Cập nhật");
        jButtonCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhatActionPerformed(evt);
            }
        });

        jButtonHuy.setText("Hủy");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonCapNhat)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHuy))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTenMonHocSua)
                            .addComponent(jLabelSoTietSua)
                            .addComponent(jLabelHeSoSua))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHeSoSua, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSoTietSua, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTenMonHocSua, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenMonHocSua)
                    .addComponent(jTextFieldTenMonHocSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSoTietSua)
                    .addComponent(jTextFieldSoTietSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHeSoSua)
                    .addComponent(jTextFieldHeSoSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCapNhat)
                    .addComponent(jButtonHuy))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, "CapNhatCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonThemActionPerformed
        newTenMonHoc = jTextFieldTenMonHoc.getText();
        newSoTiet = Integer.parseInt(jTextFieldSoTiet.getText());
        newHeSo = Float.parseFloat(jTextFieldHeSo.getText());

        newMonHoc.setTenMonHoc(newTenMonHoc);
        newMonHoc.setHeSo(newHeSo);
        newMonHoc.setSoTiet(newSoTiet);

        monHocCtrl.createMonHoc(newMonHoc);
        loadDanhSachMonHoc();
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        showPanel("CapNhatCard");
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonXoaActionPerformed
        monHocCtrl.deleteMonHocById(idMonHocDelete);
        loadDanhSachMonHoc();
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhatActionPerformed
        showPanel("DanhSachMonHocCard");
    }//GEN-LAST:event_jButtonCapNhatActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        showPanel("DanhSachMonHocCard");
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        dispose();
        HomeQuanLy homeQuanLy = new HomeQuanLy();
        homeQuanLy.setVisible(true);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jTableDanhSachMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDanhSachMonHocMouseClicked
        int x = jTableDanhSachMonHoc.getSelectedRow();
        if (x>=0) {
            idMonHocDelete = (int) jTableDanhSachMonHoc.getValueAt(x, 0);
            suaTenMonHoc = (String) jTableDanhSachMonHoc.getValueAt(x, 1);
            suaSoTiet = (Integer) jTableDanhSachMonHoc.getValueAt(x, 2);
            suaHeSo = (Float) jTableDanhSachMonHoc.getValueAt(x, 3);

            suaMonHoc.setId(idMonHocDelete);
            suaMonHoc.setTenMonHoc(suaTenMonHoc);
            suaMonHoc.setHeSo(suaHeSo);
            suaMonHoc.setSoTiet(suaSoTiet);
        }
    }//GEN-LAST:event_jTableDanhSachMonHocMouseClicked
    private void showPanel(String panelName) {

        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, panelName);
    }
    private void loadDanhSachMonHoc() throws SQLException {
        List<MonHoc> list = monHocCtrl.getAllMonHoc();
        if (danhSachMonHoc.getRowCount()>0) danhSachMonHoc.setRowCount(0);
        for (int i = 0; i< list.size(); i++) {
            int Id = list.get(i).getId();
            String tenMonHoc = list.get(i).getTenMonHoc();
            Integer soTiet = list.get(i).getSoTiet();
            Float heSo = list.get(i).getHeSo();
            Object[] row = {Id, tenMonHoc, soTiet, heSo};
            danhSachMonHoc.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonHocQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MonHocQL().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCapNhat;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabelDanhSachMonHoc;
    private javax.swing.JLabel jLabelHeSo;
    private javax.swing.JLabel jLabelHeSoSua;
    private javax.swing.JLabel jLabelSoTiet;
    private javax.swing.JLabel jLabelSoTietSua;
    private javax.swing.JLabel jLabelTenMonHoc;
    private javax.swing.JLabel jLabelTenMonHocSua;
    private javax.swing.JLabel jLabelThemMonHoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDanhSachMonHoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDanhSachMonHoc;
    private javax.swing.JTextField jTextFieldHeSo;
    private javax.swing.JTextField jTextFieldHeSoSua;
    private javax.swing.JTextField jTextFieldSoTiet;
    private javax.swing.JTextField jTextFieldSoTietSua;
    private javax.swing.JTextField jTextFieldTenMonHoc;
    private javax.swing.JTextField jTextFieldTenMonHocSua;
    // End of variables declaration//GEN-END:variables

    private MonHocDAO monHocDAO;
    private MonHocCtrl monHocCtrl;
    private MonHoc newMonHoc;
    private MonHoc suaMonHoc;
    private String newTenMonHoc;
    private int newSoTiet;
    private Float newHeSo;
    private String suaTenMonHoc;
    private Integer suaSoTiet;
    private Float suaHeSo;
    private int idMonHocDelete;
    private DefaultTableModel danhSachMonHoc;

}
