/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.QuanLy;

import com.mycompany.quanlydiemtruongthpt.Connection.MyConnection;
import com.mycompany.quanlydiemtruongthpt.Controller.HoSoHocSinhCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.KhoiLopCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.LopCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.NamHocCtrl;
import com.mycompany.quanlydiemtruongthpt.Model.HoSoHocSinh;
import com.mycompany.quanlydiemtruongthpt.Model.KhoiLop;
import com.mycompany.quanlydiemtruongthpt.Model.NamHoc;

import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class PhanLopQL extends javax.swing.JFrame {

    /**
     * Creates new form PhanLopQL
     */
    public PhanLopQL() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        khoiLopCtrl = new KhoiLopCtrl();
        lopCtrl = new LopCtrl();
        namHocCtrl = new NamHocCtrl();
        idHocSinhs = new ArrayList<>();

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxNamHocMoi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxKhoiLopMoi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxLopMoi = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLopMoi = new javax.swing.JTable();
        jButtonChuyen = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxLopCu = new javax.swing.JComboBox<>();
        jComboBoxKhoiLopCu = new javax.swing.JComboBox<>();
        jComboBoxNamHocCu = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLopCu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phân lớp học sinh");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Thông tin lớp mới");

        jLabel3.setText("Năm học:");

        jComboBoxNamHocMoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBoxNamHocMoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNamHocMoiItemStateChanged(evt);
            }
        });

        jLabel4.setText("Khối lớp:");

        jComboBoxKhoiLopMoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxKhoiLopMoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    jComboBoxKhoiLopMoiItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel5.setText("Lớp:");

        jComboBoxLopMoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxLopMoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    jComboBoxLopMoiItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(111, 111, 111))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jComboBoxNamHocMoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addComponent(jComboBoxKhoiLopMoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(72, 72, 72)
                        .addComponent(jComboBoxLopMoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxNamHocMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxKhoiLopMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxLopMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTableLopMoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ tên", "Giới tính"
            }
        ) );
        danhSachLopMoi = (DefaultTableModel) jTableLopMoi.getModel();
        jTableLopMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLopMoiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableLopMoi);
        if (jTableLopMoi.getColumnModel().getColumnCount() > 0) {
            jTableLopMoi.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonChuyen.setText("Chuyển");
        jButtonChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonChuyenActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Thông tin lớp cũ");

        jLabel6.setText("Năm học:");

        jLabel7.setText("Khối lớp:");

        jLabel8.setText("Lớp:");

        jComboBoxLopCu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxLopCu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    jComboBoxLopCuItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jComboBoxKhoiLopCu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxKhoiLopCu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    jComboBoxKhoiLopCuItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jComboBoxKhoiLopCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxKhoiLopCuMouseClicked(evt);
            }
        });

        jComboBoxNamHocCu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBoxNamHocCu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNamHocCuItemStateChanged(evt);
            }
        });
        jComboBoxNamHocCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxNamHocCuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(jComboBoxNamHocCu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(44, 44, 44)
                        .addComponent(jComboBoxKhoiLopCu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(72, 72, 72)
                        .addComponent(jComboBoxLopCu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxNamHocCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxKhoiLopCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxLopCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTableLopCu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chọn", "ID", "Họ tên", "Giới tính"
            }
        ) );
        jTableLopCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLopCuMouseClicked(evt);
            }
        });
        danhSachLopCu = (DefaultTableModel) jTableLopCu.getModel();
        jTableLopCu.getColumnModel().getColumn(0).setCellRenderer(jTableLopCu.getDefaultRenderer(Boolean.class));
        jTableLopCu.getColumnModel().getColumn(0).setCellEditor(jTableLopCu.getDefaultEditor(Boolean.class));

        jScrollPane2.setViewportView(jTableLopCu);
        if (jTableLopCu.getColumnModel().getColumnCount() > 0) {
            jTableLopCu.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(466, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonChuyen)
                        .addGap(247, 247, 247)
                        .addComponent(jButtonThoat))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        dispose();
        HomeQuanLy homeQuanLy = new HomeQuanLy();
        homeQuanLy.setVisible(true);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jComboBoxNamHocCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxNamHocCuMouseClicked

    }//GEN-LAST:event_jComboBoxNamHocCuMouseClicked

    private void jComboBoxKhoiLopCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxKhoiLopCuMouseClicked

    }//GEN-LAST:event_jComboBoxKhoiLopCuMouseClicked

    private void jComboBoxNamHocCuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNamHocCuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNamHocCuItemStateChanged

    private void jComboBoxKhoiLopCuItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_jComboBoxKhoiLopCuItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            String str = "";
            String[] parts = null;
            str = (String) jComboBoxKhoiLopCu.getSelectedItem();
            parts = str.split("-");
            idKhoiLopCu = Integer.parseInt(parts[0].trim());

            loadLopCu();
            loadDanhSachLopCu();
        }
    }//GEN-LAST:event_jComboBoxKhoiLopCuItemStateChanged

    private void jComboBoxLopCuItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_jComboBoxLopCuItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            String str = "";
            String[] parts = null;

            str = (String) jComboBoxLopCu.getSelectedItem();
            parts = str.split("-");
            idLopCu = Integer.parseInt(parts[0].trim());

            loadDanhSachLopCu();
        }
    }//GEN-LAST:event_jComboBoxLopCuItemStateChanged

    private void jComboBoxNamHocMoiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNamHocMoiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNamHocMoiItemStateChanged

    private void jComboBoxKhoiLopMoiItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_jComboBoxKhoiLopMoiItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            String str = "";
            String[] parts = null;
            str = (String) jComboBoxKhoiLopMoi.getSelectedItem();
            parts = str.split("-");
            idKhoiLopMoi = Integer.parseInt(parts[0].trim());

            loadLopMoi();
            loadDanhSachLopMoi();
        }
    }//GEN-LAST:event_jComboBoxKhoiLopMoiItemStateChanged

    private void jComboBoxLopMoiItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_jComboBoxLopMoiItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            String str = "";
            String[] parts = null;

            str = (String) jComboBoxLopMoi.getSelectedItem();
            parts = str.split("-");
            idLopMoi = Integer.parseInt(parts[0].trim());

            loadDanhSachLopMoi();
        }
    }//GEN-LAST:event_jComboBoxLopMoiItemStateChanged

    private void jButtonChuyenActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonChuyenActionPerformed
        new HoSoHocSinhCtrl().chuyenLop(idHocSinhs, idLopMoi);
        loadDanhSachLopCu();
        loadDanhSachLopMoi();
        idHocSinhs.clear();
    }//GEN-LAST:event_jButtonChuyenActionPerformed

    private void jTableLopCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLopCuMouseClicked
        if (danhSachLopCu.getRowCount()>0) {
            int columnIndex = jTableLopCu.getColumnModel().getColumnIndex("Chọn");  // Lấy thứ tự của cột "Chọn"
            int rowIndex = jTableLopCu.getSelectedRow();

            if (columnIndex == 0 && rowIndex != -1) {
                Boolean checked = (Boolean) jTableLopCu.getValueAt(rowIndex, columnIndex); // Lấy giá trị của checkbox
                int idHocSinh = (int) jTableLopCu.getValueAt(rowIndex, 1);
                if (checked) {
                    idHocSinhs.add(idHocSinh);
                };

                if (!checked) {
                    if (idHocSinhs.contains((Integer) idHocSinh)) idHocSinhs.remove((Integer) idHocSinh);
                }
            }
        }
    }//GEN-LAST:event_jTableLopCuMouseClicked

    private void jTableLopMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLopMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLopMoiMouseClicked

    private void loadNamHocCuKhoiLopCu() throws SQLException {
        jComboBoxNamHocCu.removeAllItems();
        jComboBoxKhoiLopCu.removeAllItems();

//        jComboBoxNamHocCu.setEnabled(false);
        List<NamHoc> namHocs = namHocCtrl.getAllNamHoc();
        for (int i = 0; i<namHocs.size(); i++) {
            jComboBoxNamHocCu.addItem(namHocs.get(i).getTenNamHoc());
        }
//        jComboBoxNamHocCu.setEnabled(true);

//        jComboBoxKhoiLopCu.setEnabled(false);
        List<KhoiLop> khoiLops = khoiLopCtrl.getAllKhoiLop();
        for (int i = 0; i<khoiLops.size(); i++) {
            jComboBoxKhoiLopCu.addItem(khoiLops.get(i).getId()+"-"+khoiLops.get(i).getTenKhoiLop());
        }
//        jComboBoxKhoiLopCu.setEnabled(true);

        namHocCu = (String) jComboBoxNamHocCu.getSelectedItem();
//

        String str = "";
        String[] parts = null;
        str = (String) jComboBoxKhoiLopCu.getSelectedItem();
        parts = str.split("-");
        idKhoiLopCu = Integer.parseInt(parts[0].trim());
        loadLopCu();
        str = (String) jComboBoxLopCu.getSelectedItem();
        parts = str.split("-");
        idLopCu = Integer.parseInt(parts[0].trim());

    }

    private void loadNamHocMoiKhoiLopMoi() throws SQLException {
        jComboBoxKhoiLopMoi.removeAllItems();
        jComboBoxNamHocMoi.removeAllItems();

//        jComboBoxNamHocMoi.setEnabled(false);
        List<NamHoc> namHocs = namHocCtrl.getAllNamHoc();
        for (int i = 0; i<namHocs.size(); i++) {
            jComboBoxNamHocMoi.addItem(namHocs.get(i).getTenNamHoc());
        }
//        jComboBoxNamHocMoi.setEnabled(true);

//        jComboBoxKhoiLopMoi.setEnabled(false);
        List<KhoiLop> khoiLops = khoiLopCtrl.getAllKhoiLop();
        for (int i = 0; i<khoiLops.size(); i++) {
            jComboBoxKhoiLopMoi.addItem(khoiLops.get(i).getId()+"-"+khoiLops.get(i).getTenKhoiLop());
        }
//        jComboBoxKhoiLopMoi.setEnabled(true);

        //
        namHocMoi = (String) jComboBoxNamHocMoi.getSelectedItem();
        String str = "";
        String[] parts = null;
        str = (String) jComboBoxKhoiLopMoi.getSelectedItem();
        parts = str.split("-");
        idKhoiLopMoi = Integer.parseInt(parts[0].trim());
        loadLopMoi();
        str = (String) jComboBoxLopMoi.getSelectedItem();
        parts = str.split("-");
        idLopMoi = Integer.parseInt(parts[0].trim());

    }

    private void loadLopCu () throws SQLException {
        jComboBoxLopCu.removeAllItems();
        int idNamHocCu = namHocCtrl.getIdNamHocByName(namHocCu);
        String getLop = "SELECT * FROM LOP WHERE KhoiLop_Id = "+idKhoiLopCu+" and NamHoc_Id = "+idNamHocCu;
        ResultSet resultSet = MyConnection.ExcuteQueryGetTable(getLop);
        while (resultSet.next()) {
            jComboBoxLopCu.addItem(resultSet.getInt("Lop_Id")+"-"+resultSet.getString("TenLop"));
        }
    }

    private void loadLopMoi () throws SQLException {
        jComboBoxLopMoi.removeAllItems();
        int idNamHocMoi = namHocCtrl.getIdNamHocByName(namHocMoi);
        String getLop = "SELECT * FROM LOP WHERE KhoiLop_Id = "+idKhoiLopMoi+" and NamHoc_Id = "+idNamHocMoi;
        ResultSet resultSet = MyConnection.ExcuteQueryGetTable(getLop);
        while (resultSet.next()) {
            jComboBoxLopMoi.addItem(resultSet.getInt("Lop_Id")+"-"+resultSet.getString("TenLop"));
        }
    }

    private void loadDanhSachLopCu () throws SQLException {
        if (danhSachLopCu.getRowCount()>0)danhSachLopCu.setRowCount(0); else {
            Object[] row = {false, "Trống"};
            danhSachLopCu.addRow(row);
        }
        List<HoSoHocSinh> hoSoHocSinhs = lopCtrl.getAllHocSinhByIdLop(idLopCu);
        for (int i = 0; i<hoSoHocSinhs.size(); i++) {
            int idHocSinh = hoSoHocSinhs.get(i).getId();
            String tenHocSinh = hoSoHocSinhs.get(i).getHoTen();
            String gioiTinh = hoSoHocSinhs.get(i).getGioiTinh();

            Object[] row = {false, idHocSinh, tenHocSinh, gioiTinh};
            danhSachLopCu.addRow(row);
        }
    }

    private void loadDanhSachLopMoi () throws SQLException {
        if (danhSachLopMoi.getRowCount()>0)danhSachLopMoi.setRowCount(0);
        List<HoSoHocSinh> hoSoHocSinhs = lopCtrl.getAllHocSinhByIdLop(idLopMoi);
        for (int i = 0; i<hoSoHocSinhs.size(); i++) {
            int idHocSinh = hoSoHocSinhs.get(i).getId();
            String tenHocSinh = hoSoHocSinhs.get(i).getHoTen();
            String gioiTinh = hoSoHocSinhs.get(i).getGioiTinh();

            Object[] row = {idHocSinh, tenHocSinh, gioiTinh};
            danhSachLopMoi.addRow(row);
        }
    }

    private void loadData () throws SQLException {
        loadNamHocCuKhoiLopCu();
        loadNamHocMoiKhoiLopMoi();

        //
        loadDanhSachLopCu();
        loadDanhSachLopMoi();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanLopQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanLopQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanLopQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanLopQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PhanLopQL().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChuyen;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JComboBox<String> jComboBoxKhoiLopCu;
    private javax.swing.JComboBox<String> jComboBoxKhoiLopMoi;
    private javax.swing.JComboBox<String> jComboBoxLopCu;
    private javax.swing.JComboBox<String> jComboBoxLopMoi;
    private javax.swing.JComboBox<String> jComboBoxNamHocCu;
    private javax.swing.JComboBox<String> jComboBoxNamHocMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableLopCu;
    private javax.swing.JTable jTableLopMoi;
    // End of variables declaration//GEN-END:variables
    private NamHocCtrl namHocCtrl;
    private KhoiLopCtrl khoiLopCtrl;
    private LopCtrl lopCtrl;

    private DefaultTableModel danhSachLopCu;
    private DefaultTableModel danhSachLopMoi;
    List<Integer> idHocSinhs;

    private String namHocCu;
    private int idKhoiLopCu;
    private int idLopCu;
    private String namHocMoi;
    private int idKhoiLopMoi;
    private int idLopMoi;


}
