/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemtruongthpt.UI.QuanLy;

import com.mycompany.quanlydiemtruongthpt.Connection.MyConnection;
import com.mycompany.quanlydiemtruongthpt.Controller.GiaoVienCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.LopCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.MonHocCtrl;
import com.mycompany.quanlydiemtruongthpt.Controller.PhanLopCtrl;
import com.mycompany.quanlydiemtruongthpt.Model.GiaoVien;
import com.mycompany.quanlydiemtruongthpt.Model.Lop;
import com.mycompany.quanlydiemtruongthpt.Model.MonHoc;

import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class PhanCongQL extends javax.swing.JFrame {

    /**
     * Creates new form PhanCongQL
     */
    public PhanCongQL() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        phanLopCtrl = new PhanLopCtrl();
        monHocCtrl = new MonHocCtrl();
        giaoVienCtrl = new GiaoVienCtrl();
        lopCtrl = new LopCtrl();


        jPanelPhanCongGiangDay = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonXemChiTiet = new javax.swing.JButton();
        jButtonChinhSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachGiangDay = new javax.swing.JTable();
        jButtonThoat = new javax.swing.JButton();
        jPanelDanhSachGiangDay = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMonHoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxGiaoVien = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLop = new javax.swing.JComboBox<>();
        jButtonPhanCong = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phân công giáo viên");

        jPanelPhanCongGiangDay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setText("Danh sách giảng dạy");

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        jButtonXemChiTiet.setText("Xem chi tiết");
        jButtonXemChiTiet.setFocusable(false);
        jButtonXemChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonXemChiTiet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXemChiTietActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonXemChiTiet);

        jButtonChinhSua.setText("Chỉnh sửa");
        jButtonChinhSua.setFocusable(false);
        jButtonChinhSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonChinhSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChinhSuaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonChinhSua);

        jButtonXoa.setText("Xóa");
        jButtonXoa.setFocusable(false);
        jButtonXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonXoaActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jToolBar1.add(jButtonXoa);

        jTableDanhSachGiangDay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Giáo viên", "Lớp", "Môn Học"
            }
        ) );
        jTableDanhSachGiangDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDanhSachGiangDayMouseClicked(evt);
            }
        });
        danhSachGiangDay = (DefaultTableModel) jTableDanhSachGiangDay.getModel();
        jScrollPane1.setViewportView(jTableDanhSachGiangDay);
        if (jTableDanhSachGiangDay.getColumnModel().getColumnCount() > 0) {
            jTableDanhSachGiangDay.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPhanCongGiangDayLayout = new javax.swing.GroupLayout(jPanelPhanCongGiangDay);
        jPanelPhanCongGiangDay.setLayout(jPanelPhanCongGiangDayLayout);
        jPanelPhanCongGiangDayLayout.setHorizontalGroup(
            jPanelPhanCongGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhanCongGiangDayLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(194, 194, 194))
            .addGroup(jPanelPhanCongGiangDayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPhanCongGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhanCongGiangDayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonThoat)
                .addContainerGap())
        );
        jPanelPhanCongGiangDayLayout.setVerticalGroup(
            jPanelPhanCongGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhanCongGiangDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonThoat)
                .addGap(125, 125, 125))
        );

        jPanelDanhSachGiangDay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Môn học:");

        jComboBoxMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMonHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    jComboBoxMonHocItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel2.setText("Giáo viên:");

        jComboBoxGiaoVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGiaoVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxGiaoVienItemStateChanged(evt);
            }
        });

        jLabel3.setText("Lớp:");

        jComboBoxLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxLopItemStateChanged(evt);
            }
        });

        jButtonPhanCong.setText("Phân công");
        jButtonPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonPhanCongActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Phân công giảng dạy");

        javax.swing.GroupLayout jPanelDanhSachGiangDayLayout = new javax.swing.GroupLayout(jPanelDanhSachGiangDay);
        jPanelDanhSachGiangDay.setLayout(jPanelDanhSachGiangDayLayout);
        jPanelDanhSachGiangDayLayout.setHorizontalGroup(
            jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachGiangDayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelDanhSachGiangDayLayout.createSequentialGroup()
                        .addGroup(jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGiaoVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxMonHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelDanhSachGiangDayLayout.createSequentialGroup()
                                .addGroup(jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jButtonPhanCong))
                                .addGap(0, 99, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelDanhSachGiangDayLayout.setVerticalGroup(
            jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachGiangDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDanhSachGiangDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonPhanCong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDanhSachGiangDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPhanCongGiangDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDanhSachGiangDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPhanCongGiangDay, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemChiTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXemChiTietActionPerformed

    private void jButtonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChinhSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChinhSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonXoaActionPerformed
        phanLopCtrl.deletePhanLopById(idDelete);
        loadDanhSachGiangDay();
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        dispose();
        HomeQuanLy homeQuanLy = new HomeQuanLy();
        homeQuanLy.setVisible(true);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonPhanCongActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPhanCongActionPerformed
        phanLopCtrl.phanLop(idGiaoVien, idLop);
        loadDanhSachGiangDay();
    }//GEN-LAST:event_jButtonPhanCongActionPerformed

    private void jComboBoxMonHocItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_jComboBoxMonHocItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            String str = "";
            String[] parts = null;
            str = (String) jComboBoxMonHoc.getSelectedItem();
            parts = str.split("-");
            idMonHoc = Integer.parseInt(parts[0].trim());

            loadGiaoVien();

        }
    }//GEN-LAST:event_jComboBoxMonHocItemStateChanged

    private void jComboBoxGiaoVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxGiaoVienItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String str = (String) jComboBoxGiaoVien.getSelectedItem();
            String[] parts = str.split("-");
            idGiaoVien = Integer.parseInt(parts[0].trim());
        }
    }//GEN-LAST:event_jComboBoxGiaoVienItemStateChanged

    private void jComboBoxLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxLopItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String str = (String) jComboBoxLop.getSelectedItem();
            String[] parts = str.split("-");
            idLop = Integer.parseInt(parts[0].trim());
        }
    }//GEN-LAST:event_jComboBoxLopItemStateChanged

    private void jTableDanhSachGiangDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDanhSachGiangDayMouseClicked
        int x = jTableDanhSachGiangDay.getSelectedRow();
        if (x>=0) {
            idDelete = (int) jTableDanhSachGiangDay.getValueAt(x, 0);
        }
    }//GEN-LAST:event_jTableDanhSachGiangDayMouseClicked

    private void loadMonHoc() throws SQLException {
        jComboBoxMonHoc.removeAllItems();
        List<MonHoc> monHocs = monHocCtrl.getAllMonHoc();
        for (int i = 0; i<monHocs.size(); i++) {
            jComboBoxMonHoc.addItem(monHocs.get(i).getId()+"-"+monHocs.get(i).getTenMonHoc());
        }
        if (jComboBoxMonHoc.getItemCount() > 0) {
            String str = (String) jComboBoxMonHoc.getSelectedItem();
            String[] parts = str.split("-");
            idMonHoc = Integer.parseInt(parts[0].trim());
        }
    }

    private void loadGiaoVien() throws SQLException {

        jComboBoxGiaoVien.removeAllItems();
        String getGiaoViensSql = "SELECT * FROM GIAOVIEN WHERE MonHoc_Id = "+idMonHoc;
        ResultSet resultSet = MyConnection.ExcuteQueryGetTable(getGiaoViensSql);

        while (resultSet.next()) {
            String giaovien = resultSet.getInt("GiaoVien_Id")+"-"+ resultSet.getInt("GiaoVien_Id")+resultSet.getString("HoTen");
            jComboBoxGiaoVien.addItem(giaovien);
        }

        if (jComboBoxGiaoVien.getItemCount() > 0) {

            String giaovien = (String) jComboBoxGiaoVien.getSelectedItem();
            String[] parts = giaovien.split("-");
            idGiaoVien = Integer.parseInt(parts[0].trim());
        }
    }

    private void loadLop() throws SQLException {
        jComboBoxLop.removeAllItems();
        List<Lop> lops = new ArrayList<>();
        lops = lopCtrl.getAllLop();
        for (int i = 0; i<lops.size(); i++) {
            String lop = lops.get(i).getId()+"-"+lops.get(i).getTenLop();
            jComboBoxLop.addItem(lop);
        }
        if (jComboBoxLop.getItemCount()>0) {
            String lop = (String) jComboBoxLop.getSelectedItem();
            String[] parts = lop.split("-");
            idLop = Integer.parseInt(parts[0].trim());
        }

    }

    private void loadDanhSachGiangDay() throws SQLException {
        if (danhSachGiangDay.getRowCount()>0) danhSachGiangDay.setRowCount(0);
        String sqlgetDanhSachPhanCong = "SELECT PhanLop_Id, HoTen, TenLop,  PHANLOP.GiaoVien_Id as GiaoVien_Id  FROM PHANLOP\n" +
                "LEFT JOIN GIAOVIEN ON PHANLOP.GiaoVien_Id = GIAOVIEN.GiaoVien_Id \n" +
                "LEFT JOIN LOP ON PHANLOP.Lop_Id = LOP.Lop_Id;";

        ResultSet resultSet = MyConnection.ExcuteQueryGetTable(sqlgetDanhSachPhanCong);
        while (resultSet.next()) {
            int id = resultSet.getInt("PhanLop_Id");
            String tenGiaoVien = resultSet.getString("HoTen");
            String tenLop = resultSet.getString("TenLop");
            String tenMonHoc = giaoVienCtrl.getTenMonHocIdGiaoVien(resultSet.getInt("GiaoVien_Id"));
            Object[] row = {id, tenGiaoVien, tenLop, tenMonHoc};
            danhSachGiangDay.addRow(row);
        }
    }
    private void loadData() throws SQLException {
        loadMonHoc();
        loadGiaoVien();
        loadLop();
        loadDanhSachGiangDay();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanCongQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanCongQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanCongQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanCongQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PhanCongQL().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChinhSua;
    private javax.swing.JButton jButtonPhanCong;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXemChiTiet;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBoxGiaoVien;
    private javax.swing.JComboBox<String> jComboBoxLop;
    private javax.swing.JComboBox<String> jComboBoxMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelDanhSachGiangDay;
    private javax.swing.JPanel jPanelPhanCongGiangDay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableDanhSachGiangDay;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private MonHocCtrl monHocCtrl;
    private GiaoVienCtrl giaoVienCtrl;
    private LopCtrl lopCtrl;

    private int idMonHoc;
    private int idGiaoVien;
    private int idLop;
    private DefaultTableModel danhSachGiangDay;
    private PhanLopCtrl phanLopCtrl;
    private int idDelete;

}
